### PR TITLE
Updating report  checklist that shows up in pull requests.

### PR DESCRIPTION
**Pull request by wfulp**
I'm making this pull request so we can jointly update the report checklist to incorporate all the items we would like. It would be nice to have all PT report checklist items in one place that can be updated as needed.

I also changed template txt to md file. I don't think there are any issues with this:
https://help.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository

### CODE REVIEW

**Comment by monicagerber** [comment]
@wfulp Thanks for opening the PR! I am waiting until we discuss as a group on Thursday to review/respond.

**Comment by wfulp** [comment]
If I understand the next steps coming out of our discussion, this `pull_request_template.md` file will become code review and writing review links, along with instructions. 

Should the actual checklists go somewhere for people to review and comment (Notion)?

**Comment by monicagerber** [comment]
Yes, that's my understanding too! 

I think we should put them in the VISC-Documentation repo.
* Writing: https://github.com/FredHutch/VISC-Documentation/tree/master/Writing_Reviewing
* Programming: https://github.com/FredHutch/VISC-Documentation/tree/master/Programming

We could have people comment through the PR. What do you think?

**Comment by monicagerber** [comment]
@wfulp I made some changes to `pull_request_template.md` based on what we discussed. Let me know what you think.

**Comment by wfulp** [comment]
> @wfulp I made some changes to `pull_request_template.md` based on what we discussed. Let me know what you think.

Changes look great

**Comment by monicagerber** [comment]
Great, thanks @wfulp! Will merge PR.

**Pull request merged**
