### PR TITLE
CI check for #168

### PR DESCRIPTION
**Pull request by slager**
DO NOT MERGE. This branch is just #168 with the bugfix from #159 merged in, to see if the CI runners can successfully test knit the generic report.

### CODE REVIEW

**Comment by slager** [comment]
Yay, the generic reports knit across all CI platforms with Kellie's bugfix.

**Comment by kelliemac** [comment]
sweet! just noting that I've looked at this and am happy to see that with the bugfix everything is running smoothly!

**Comment by slager** [comment]
Closing, but leaving the branch here for now.

**Comment by slager** [comment]
Deleting branch since there hasn't been movement on this from upstream. Will resurrect later as needed.

**Pull request closed without merging**
