### PR TITLE
Nicer formatting for report .docx files

### PR DESCRIPTION
**Pull request by kelliemac**
I updated the Word document style reference file to provide better formatting for the PT report .docx files. I used this version in creating the G002 B cell PT report. Unfortunately it is difficult to track all of the changes in .docx files like this using git, but here is a summary of the differences:

- Smaller margins
- Improved formatting for table of contents
- Changed color scheme to use the Fred Hutch colors (e.g., for header text color)
- Updated fonts to be consistent throughout document

### CODE REVIEW

**Comment by kelliemac** [comment]
You can see a basic example of the updated word document formatting by downloading the zip file containing PDF and docx skeleton reports (generated by GitHub actions automatically once this pull request was created) by clicking here: https://github.com/FredHutch/VISCtemplates/actions/runs/8486161235/artifacts/1370732079

**Comment by kelliemac** [comment]
@mayerbry this is still draft status since we need to run the word document formatting by Solmaz, but feel free to take a look at the suggested changes anytime. you can see the new CI feature in action too (check out my previous comment)!

**Comment by slager** [comment]
Merged `develop` into this branch, as mentioned in the plan for #175.

This PR is now docx changes only, and is being test-knitted by the new CI.

**Comment by kelliemac** [comment]
I will update this branch and PR soon. I have been testing out changes with the C101 B-cell report so I can incorporate those changes once the report is finished. Probably will get to this sometime next week.

**Comment by slager** [comment]
This might be a good PR in which to also tackle #174, if straightforward.

**Comment by kelliemac** [comment]
Abandoning this PR in favor of https://github.com/FredHutch/VISCtemplates/pull/183

**Pull request closed without merging**
