### PR TITLE
Tweaks and tests for adding visc_load_pdata()

### PR DESCRIPTION
**Pull request by slager**
- A few tweaks found while running `devtools::check()`
- Namespace tweaks
- Add tests for `visc_load_pdata()`

### CODE REVIEW

**Comment by mayerbry** [comment]
Hello,

I've had trouble using this function that might be Mac related, most recently (12:30pm on 4/26) I sourced from [here](https://github.com/FredHutch/VISCtemplates/blob/b6bc8a3451c44b5c94ae9d9a25e315104c647a38/R/visc_load_pdata.R) and ran the following

```
library(Caskey820)
Caskey820_bama <- visc_load_pdata(Caskey820_bama_bds, criteria = "5d3fe6542a3a6517bdb2dc9e6b644d74")
```

and got the following error:
```
Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file '/Users/bmayer/Library/R/x86_64/4.3/library/Caskey820/data/Caskey820_bama_bds.rda', probable reason 'No such file or directory'
```

**Comment by slager** [comment]
@mayerbry Do you get the same error when you restart your R session and then do this?

```
remotes::install_github("FredHutch/VISCtemplates", ref = "dave")
library(VISCtemplates)
library(Caskey820)
Caskey820_bama <- visc_load_pdata(Caskey820_bama_bds, criteria = "5d3fe6542a3a6517bdb2dc9e6b644d74")
```

**Comment by slager** [comment]
This should be a better way.  Added some tests for it as well.

**Comment by mayerbry** [comment]
works fine in the update!

FYI:
```
Sys.getenv("R_LIBS_USER")
[1] "/Users/bmayer/Library/R/x86_64/4.3/library"
```

**Review by valduran18 — APPROVED** [review]
looks great. Thanks, Dave!

**Pull request merged**
