### PR TITLE
Update git_obj_compare_fun.R

### PR DESCRIPTION
**Pull request by valduran18**
added an internal use function `obj_compare` that updates the output of diffdf, giving the user the option of either outputting the default settings, or only the warning message. If no differences are found, a character string message is returned instead of the default list. `obj_compare` is then used in `git_object_compare`

### CODE REVIEW

**Comment by valduran18** [comment]
one thing to note is that this function runs much faster on server:

image

vs

**Comment by valduran18** [comment]
`odb_blobs()` on my local RStudio took ~30 min to run
image

**Comment by valduran18** [comment]
> `odb_blobs()` on my local RStudio took ~30 min to run image

one possible solution is to change `odb_blobs()` to `system2("git" ,"ls-files '*.rda'" , stdout = TRUE)`

**Comment by slager** [comment]
Workflow:

@valduran18 

If we want to include these changes in `develop`, we should:
1) merge this PR into `git_object_compare`, and then
2) merge #149 into `develop`

**Pull request closed without merging**
