### PR TITLE
Improve word document formatting, including table formatting

### PR DESCRIPTION
**Pull request by kelliemac**
Updating word-styles-reference.docx for improved formatting in Word versions of reports.

Cleaning up template.tex as well: deleting commented-out code, reordering lines so that related code is grouped together, adding comments on what particular latex packages are used for. All in hopes that future updates to the latex template will be faster/smoother.

### CODE REVIEW

**Comment by kelliemac** [comment]
Related to issues: https://github.com/FredHutch/VISCtemplates/issues/161 and https://github.com/FredHutch/VISCtemplates/issues/120

**Comment by kelliemac** [comment]
The tables were looking bad in the Word reports, so I'm converting this PR to draft and working on incorporating a fix for that (related to https://github.com/FredHutch/VISCtemplates/issues/120)

**Comment by kelliemac** [comment]
@slager can you help figure out how the statsrv runner needs to be updated to get that test passing, now that you've been able to install flextable on statsrv itself? you're welcome to commit directly to this branch.

I'm going to keep thinking about whether to switch from flextable to gt, so no rush on this. it sounded like you had an idea of what needed to be fixed, so I'm assuming you'll be way more efficient at fixing it than I will.

**Comment by slager** [comment]
Sure!

**Comment by slager** [comment]
The installation issue is now fixed! On the statsrv runner it is necessary to manually install the package dependencies that are not yet listed in the DESCRIPTION in the main branch of VISCtemplates, since those don't get found by remotes::install_github(). We can remove those manual installs from the statsrv CI on develop after we do another release/merge to main.

It's knitting on all platforms now but failing due to some test warnings about a missing label. There are also some R CMD check notes about the `%>%` pipes. It might be better to implement this without adding a direct dependency on magrittr/dplyr and without using the magrittr pipes.

**Comment by slager** [comment]
When I started working on removing dplyr/magrittr here, I noticed that there are a couple of other problems probably worth fixing first.
- There is an issue with rendering some wide tables that run off the right side of the page
- My most recent commit additionally breaks the yellow highlighting in the magnitudes table, which comes from pretty_pvalues().

**Comment by kelliemac** [comment]
just split off the latex template cleanup into a separate PR (https://github.com/FredHutch/VISCtemplates/pull/196). updating this PR's title accordingly

**Comment by slager** [comment]
Note before eventual merging to be sure to check the header logos, which are not currently up to date with `develop`. See notes in #195.

**Comment by kelliemac** [comment]
closing this PR so I can open a new, simplified one from a new branch

**Pull request closed without merging**
