### PR TITLE
add visc_load_pdata function to keep in a centralized location

### PR DESCRIPTION
**Pull request by valduran18**
Closes issue #146. @slager @lemireg please review when you can

### CODE REVIEW

**Review by slager — CHANGES_REQUESTED** [review]
1) It looks good; my suggested tweaks are in #148 
2) Do we want to merge this into develop first?

**Review by slager — APPROVED** [review]

**Comment by lemireg** [comment]
Looking at the "Files Changed" tab this looks great! Glad to see this function in a centralized location. 

To clarify @valduran18: this **will not** put `visc_load_pdata` into the individual datapackages or analysis repos, but **it will** allow individuals to copy the validated version of this file into their individual repositories (whether it's a datapackage the STP is working on or the analysis repo the SRA is working on?) 

If so, I will add the location of this file in the powerpoint discussing how to incorporate it into analysis repos.

**Comment by slager** [comment]
@lemireg 

This will typically be used as follows, so knowing the URL of this script shouldn't be necessary:

```
remotes::install_github('FredHutch/VISCtemplates') # first time only
remotes::install_local('/networks/cavd/Studies/cvd820/pdata/Caskey820.git') # first time you need the data package only
library(VISCtemplates)
library(Caskey820)
Caskey820_bama <- visc_load_pdata(Caskey820_bama_bds, criteria = "5d3fe6542a3a6517bdb2dc9e6b644d74")
... analysis using the `Caskey820_bama` variable now in your R global workspace ...
```

**Review by lemireg — APPROVED** [review]

**Comment by lemireg** [comment]
> @lemireg
> 
> This will typically be used as follows, so knowing the URL of this script shouldn't be necessary:
> 
> ```
> remotes::install_github('FredHutch/VISCtemplates') # first time only
> remotes::install_local('/networks/cavd/Studies/cvd820/pdata/Caskey820.git') # first time you need the data package only
> library(VISCtemplates)
> library(Caskey820)
> Caskey820_bama <- visc_load_pdata(Caskey820_bama_bds, criteria = "5d3fe6542a3a6517bdb2dc9e6b644d74")
> ... analysis using the `Caskey820_bama` variable now in your R global workspace ...
> ```

Very neat! Even more nifty than I thought. Great, I will start implementing this, thank you.

**Pull request merged**
