### PR TITLE
add section number to References

### PR DESCRIPTION
**Pull request by slager**
Addresses #123.

### CODE REVIEW

**Comment by kelliemac** [comment]
This seems to work for pdf output, but there is no References section header in the docx output (for example, the bama docx output).

**Comment by slager** [comment]
Good catch, I forgot to check the Word output! Will think about this a little more.

**Comment by kelliemac** [comment]
FWIW, the lack of numbering on this section seems to be desired behavior:

Rmarkdown cookbook: https://bookdown.org/yihui/rmarkdown-cookbook/unnumbered-sections.html

Pandoc manual: https://pandoc.org/MANUAL.html#placement-of-the-bibliography

**Comment by kelliemac** [comment]
Based on the pandoc manual I linked, I suspect if we change the section title to something other than "References" (maybe "Report References"?) the behavior will change

**Comment by slager** [comment]
Is this an example of something that would be a nice-to-have, but isn't worth fighting the default behavior for?

**Comment by kelliemac** [comment]
that's how I see it, but I think @asatofh had the original request so we should see what she thinks! I think this is at least lower priority than other issues, though.

**Comment by slager** [comment]
I asked @asatofh and she said it's a nice-to-have for PDF, and not important for Word.

But when I went in to start conditionally adding the section number for PDF, I realized that Word already has a numbered References section!

So actually, we're golden @kelliemac if I use my first workaround conditional on PDF and maintain the existing way for DOCX.

Which is what I've now implemented here.

**Comment by kelliemac** [comment]
looks great! good idea.

**Review by kelliemac — APPROVED** [review]

**Pull request merged**
