### PR TITLE
New FH logo for Word template

### PR DESCRIPTION
**Pull request by kelliemac**
I previously updated the Fred Hutch logo for the VISC PDF template, and am now adding it for the Word template as well. I tested with a report on my end and all seems good to go! The only change was swapping the image in the word template header, nothing else.

### CODE REVIEW

**Comment by mariev** [comment]
@kelliemac do we know why the ci checks are failing? for some reason the logs aren't showing for me 😬

**Comment by kelliemac** [comment]
@mariev here is the error I see on the macOS check (for example):

Warning: r-lib/actions/setup-r@v1 is deprecated. Please update your workflow to use the 'v2' version. Also look at the examples at https://github.com/r-lib/actions/tree/v2/examples because '@v2' workflows are much simpler than 'v1' workflows.
/usr/local/bin/brew install qpdf pkgconfig checkbashisms
Error: Failed to get R 4.3.0: Failed to get R 4.3.0: Failed to download version 4.3.0: Error: Unexpected HTTP response: 404

I think your PR from today addresses this issue with the CI, so let's get that one approved and merged and see if that fixes the issue here too! (I think it will.)

**Review by mariev — CHANGES_REQUESTED** [review]
@kelliemac  can you pull the updates from main down to this branch? I think that should address everything

**Comment by kelliemac** [comment]
@mariev done! checks are passing now.

**Review by mariev — APPROVED** [review]
Thank you!

**Pull request merged**
